### ISSUE TITLE
Undefined object in JSONSever class

### ISSUE THREAD

**Issue by aim1956** [Dyalog/JSONServer#3]
.JSONServer class:
14:VALUE ERROR: Undefined name: Error
Server[19] Log'RunServer: DRC.Wait reported error ',(⍕#.Conga.Error 4⊃wres),' on ',(2⊃wres),GetIP obj
                                                              ∧
It looks like as latest Conga does not have the Error method. DRC does.

**Comment by bpbecker** [comment]
Hi Alexey,

 

Yeah, when Conga v3.2 was published the Error function was moved.

I'd made an update to MiServer to accommodate that, but hadn't done so for JSONServer.

I've fixed this and updated JSONServer to version 1.5.

 

I hope this helps!

/Brian
