### ISSUE TITLE
VALUE ERROR in Server.dome

### ISSUE THREAD

**Issue by aim1956** [Dyalog/JSONServer#4]
Dyalog APL/W-64 Version 17.1.36563
Serial No : 001296
Unicode Edition
Beta release
Thu Aug  1 13:47:40 2019
    
      )clear
clear ws
      ⎕PW←1000
      )ns Zodiac
#.Zodiac
      ]load /devt/JSONServer/Sample/* -target=Zodiac

      ⎕VR 'Zodiac.GetSign'

      Zodiac.GetSign 10 31
VALUE ERROR: Undefined name: GetSign
      Zodiac.GetSign 10 31
             ∧

It looks like as the problem is the path specified in the ]load command.

**Comment by bpbecker** [comment]
I'm going to close this issue because it's not a problem with JSONServer.

Make sure that your path is correct and the .dyalog files actually exist.  The ]load should display a list of all the loaded objects.

          )clear
    clear ws
          ⎕PW←1000
          )ns Zodiac
    #.Zodiac
          ]load /git/JSONServer/Sample/* -target=Zodiac
     GetSign  GetSignObject  GetSignWithRequest  Reverse 

]SALT.list can list the contents of the folder

          ]SALT.list /git/JSONServer/Sample/*
     Type   Name                Versions  Size  Last Update         
            GetSign                        360  2019/07/26 11:08:06 
            GetSignObject                  139  2019/07/26 11:08:06 
            GetSignWithRequest             498  2019/07/26 11:08:06 
     <DIR>  Utils                               2019/07/26 11:08:06
